### ISSUE TITLE
Isolate branches

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/sal-scripts#37]
Different brnaches of the project are not isolated in terms of SAL-scripts.

R1 branch has references main branch. For instance, line 5 in https://github.com/eu-nebulous/sal-scripts/blob/r1/installation-scripts-onm/MASTER_PRE_INSTALL_SCRIPT.sh

It is important to achieve this isolation for the prod environment

**Comment by yoctozepto** [comment]
I said this several times before. We should *stop* downloading the scripts ad-hoc - they are now well-distributed with NebulOuS. Those versions should be used instead. I don't know what is stopping us from using them directly. cc @ankicabarisic is this SAL/ProActive limitation? This is how Ali originally made them work but this is wrong for isolation and reproducibility.

**Comment by robert-sanfeliu** [comment]
SAL is using the scripts distributed with the SAL pod (MASTER_PRE_INSTALL_SCRIPT.sh, MASTER_START_SCRIPT.sh, etc...) but, these scripts make references to other scripts that are in Github. For instance, https://github.com/eu-nebulous/sal-scripts/blob/r1/installation-scripts-onm/MASTER_PRE_INSTALL_SCRIPT.sh 

```
sudo -H -u ubuntu bash -c 'wget https://raw.githubusercontent.com/eu-nebulous/overlay-network-manager/main/network-manager/bootstrap-agent-scripts/onm/onm-bootstrap.sh && chmod +x onm-bootstrap.sh'
```

**Comment by ankicabarisic** [comment]
@yoctozepto I dont understand, there is nothing to do with SAL or ProActive. When you deploy sal YOU set which scripts are loaded in kubernetes deployment .yaml file.

**Comment by yoctozepto** [comment]
@ankicabarisic It is not a matter of a volume/configmap. They are currently distributed in images but that is not the point. SAL gets access to all the scripts locally but the scripts somehow had to refer to web at the time because SAL could "see" only `MASTER_PRE_INSTALL_SCRIPT.sh`, etc. Could it somehow copy the scripts it has access to locally? Then we would not need to refer to web versions.

**Comment by ankicabarisic** [comment]
@yoctozepto @robert-sanfeliu then this does not have anything to do with SAL, as you are talking about the internal content of the scripts 

I hope that you understand that what SAL does is when you call deployCluster, it creates the deployment workflow in ProActive from the scripts which you have provided during SAL deployment. 
So you can change the links in the scripts you want to send to SAL to:
-> Point to your local script location if is accessible via `http`
OR
-> Place these scripts where is ProActive server on location `/opt/proactive/default/dist/war/rest/` and refer them in the scripts as 
`http(s)://proactive-server:port/rest/script_name`

**Comment by yoctozepto** [comment]
> @yoctozepto @robert-sanfeliu then this does not have anything to do with SAL, as you are talking about the internal content of the scripts

Not quite. The "internals" are as proposed by AE. From the discussion so far I gather they stem from the shortcomings of SAL and ProActive combination which seemingly cannot handle extra scripts beyond the preset ones.

> I hope that you understand that what SAL does is when you call deployCluster, it creates the deployment workflow in ProActive from the scripts which you have provided during SAL deployment. So you can change the links in the scripts you want to send to SAL to: -> Point to your local script location if is accessible via `http` OR -> Place these scripts where is ProActive server on location `/opt/proactive/default/dist/war/rest/` and refer them in the scripts as `http(s)://proactive-server:port/rest/script_name`

Neither option is flexible and both result in extra network transfers which could be avoided if SAL could transfer these extra scripts directly to ProActive.

---

What I see that we could have as a poor man's solution (that meets our needs but is otherwise ugly) is to avoid breaking up the main scripts into these extra downloadable ones and instead copy all the contents into the main scripts. If there are not size limits that I am unaware of, this should work just fine and avoid the branching headache. WDYT? @jmarchel7bulls @ankicabarisic @robert-sanfeliu
The added benefit is that we could also see the scripts used directly in ProActive.

**Comment by ankicabarisic** [comment]
@yoctozepto, the SAL script templates mimic the Proactive workflow for cluster deployment. I find it inappropriate to call it a shortcoming of Proactive or SAL that you are unable to organize and store installation scripts for various components into something usable by the server from different environments (accessible via http). However, this is our example, which we consider elegant, and as an integrator, you are free to test and modify the scripts in any way you prefer. However, I have not seen significant improvements in these areas since we released them.

Additionally, you can easily view the script used in the workflow by accessing it through a publicly available link. If you believe that a more 'elegant' or less 'ugly' solution would be to have a huge script that is harder to read and maintain, there are no limitations on our end regarding that.

By the way, is there any documentation available on how the SAL scripts are set up in relation to the nebulous installation for SAL, as well as the environmental variables for different components?

For further communication, I kindly request that you use a more polite and less judgmental tone when referring to our components, which are not intended to serve as an integration point.

**Comment by robert-sanfeliu** [comment]
@yoctozepto , could we set up a very lightweight http server as part of[ SAL component](https://github.com/eu-nebulous/sal/blob/main/resources/deployment.yaml) to serve the static files?  Something like nginx would be sufficient.

**Comment by yoctozepto** [comment]
> @yoctozepto, the SAL script templates mimic the Proactive workflow for cluster deployment. I find it inappropriate to call it a shortcoming of Proactive or SAL that you are unable to organize and store installation scripts for various components into something usable by the server from different environments (accessible via http).

I guess we have very different opinions on what we expect from a tool (SAL+ProActive) that is meant to deploy software to managed servers.
 
> Additionally, you can easily view the script used in the workflow by accessing it through a publicly available link.

Except it does not account for the script changing in the meantime, although rare.

> If you believe that a more 'elegant' or less 'ugly' solution would be to have a huge script that is harder to read and maintain, there are no limitations on our end regarding that.

Thanks for the confirmation.

> By the way, is there any documentation available on how the SAL scripts are set up in relation to the nebulous installation for SAL, as well as the environmental variables for different components?

I don't think this is documented beyond the actual code that sets it now up in https://github.com/eu-nebulous/helm-charts/blob/main/charts/nebulous-sal/templates/deployment.yaml

The variables that need to be set up are documented in the installation instructions and https://github.com/eu-nebulous/helmfile

> For further communication, I kindly request that you use a more polite and less judgmental tone when referring to our components, which are not intended to serve as an integration point.

I don't see where I was impolite or judgemental. I did not mean to offend you. If you mean the word "shortcoming", please blame it on my English not being native, I meant it as a synonym for "limitation" or otherwise to mean it lacks a feature I would normally expect from it.

> I'm affraid merging scripts could cause clashes in variables, and, as @ankicabarisic says, make these scripts unreadable. 

Yes, that could need untangling and it would look ugly in the end. The only upside being that it fixes this issue permanently. 🙃 

> @yoctozepto , could we set up a very lightweight http server as part of[ SAL component](https://github.com/eu-nebulous/sal/blob/main/resources/deployment.yaml) to serve the static files? Something like nginx would be sufficient.

Yes, that we could do. But then we would need to expose yet another endpoint via ingress and also pass the information where the endpoint is to the main scripts. Thus why I was looking for a more manageable solution in the first place. 😉

**Comment by ankicabarisic** [comment]
@yoctozepto thanks for sharing the link, however, I can not find a section explaining how to set environmental variables (can not even find the word environmental).

Also, I found this section: https://github.com/eu-nebulous/helmfile#external-dependency-of-nebulous---proactive-scheduler
-> This is incorrect
@robert-sanfeliu I guess we know now why the Greek company tried to get proactive over our webpage

Can you please instruct here the person to use the process recommended by Activeeon: https://github.com/eu-nebulous/nebulous/wiki/1.1-Installation-Walk%E2%80%90trough-for-Development-&-Evaluation#proactive-scheduler
Also please include here the link to instructions on how Nebulous should connect to Proactive: https://github.com/eu-nebulous/nebulous/wiki/1.1-Installation-Walk%E2%80%90trough-for-Development-&-Evaluation#configure-proactive-scheduler-details
I guess interlinking should do it!

But in any case, the documented process for scripts and the environmental vars set up for developers would be highly appreciated! Then we could probably provide additional help, for now, we have no idea how you are managing the scripts. 

Finally, regarding script changes, shouldn't you trigger the pod to pull new scripts to SAL if they change?

**Comment by yoctozepto** [comment]
> @yoctozepto thanks for sharing the link, however, I can not find a section explaining how to set environmental variables (can not even find the word environmental).

Hmm, that does document the variables that need to be set though. We might be talking about a different set of variables then!

> Also, I found this section: https://github.com/eu-nebulous/helmfile#external-dependency-of-nebulous---proactive-scheduler -> This is incorrect @robert-sanfeliu I guess we know now why the Greek company tried to get proactive over our webpage
> 
> Can you please instruct here the person to use the process recommended by Activeeon: https://github.com/eu-nebulous/nebulous/wiki/1.1-Installation-Walk%E2%80%90trough-for-Development-&-Evaluation#proactive-scheduler Also please include here the link to instructions on how Nebulous should connect to Proactive: https://github.com/eu-nebulous/nebulous/wiki/1.1-Installation-Walk%E2%80%90trough-for-Development-&-Evaluation#configure-proactive-scheduler-details I guess interlinking should do it!

🙌 I don't remember how I obtained the previous procedure details, I suspect some public repository, but I am happy to replace it.

> But in any case, the documented process for scripts and the environmental vars set up for developers would be highly appreciated! Then we could probably provide additional help, for now, we have no idea how you are managing the scripts.

The scripts are set up automatically, the users do not concern themselves with their setup. It copies the latest ones in `/usr/local/tomcat/scripts/` as instructed previously and SAL uses them fine. The other scripts are there but not copied in any meaningful directory as of now - but can be quickly made to be copied. 😉 

As for the variables... I am not sure which ones you mean (see also the first paragraph in this message).

> Finally, regarding script changes, shouldn't you trigger the pod to pull new scripts to SAL if they change?

That's what Flux CD does for all the NREC instances - it tracks the published images, updates the manifests and redeploys automatically.
